export const SET_APP = 'SET_APP';
export const REQUEST_LOGIN_USER_WITH_FB = 'REQUEST_LOGIN_USER_WITH_FB';
export const REQUEST_CREATE_USER_WITH_FB = 'REQUEST_CREATE_USER_WITH_FB';
export const REQUEST_LOGOUT_USER_WITH_FB = 'REQUEST_LOGOUT_USER_WITH_FB';
export const REQUEST_GET_ALL_PRODUCTS = 'REQUEST_GET_ALL_PRODUCTS';
